### ISSUE TITLE
Win Turbo - sort of.

### ISSUE THREAD

**Issue by dlannan** [kernelsauce/turbo#145] opened 2014-09-28 04:34 UTC
Hi kernelsauce - I wasn't sure where to put this.
Im working through some issues and I would like to warn _everyone_ this is extremely prototype. Its works, in general. But it has a number of specific 'hacks' to make it work and I need to work with the turbo author to determine the best ways to refit a solution that is more cross platform and better implemented.

Things to be very wary of:
- The Poll system has been gutted - it works, but its missing all the error systems (I had all sorts of issues with it). 
- The implementation currently uses a mish-mash of Network-tcp-server ffi and Lua syscall. I intend to move it all to the lightweight Lua systcall ( this is how the original turbo mostly works - using linux based system calls).
- WebDruino is built for mainly locally serving an Arduino and ITS NOT COMPLETE. Dont expect too much of it to work.
So. Its all a work in progress - but I wanted to get access for kernelsauce, there may be some things that can be used. Im not certain at the moment, but once Network-tcp-server is removed it should almost be a pure turbo system with minor changes in the polling and socket areas.

https://github.com/dlannan/webdruino.git
Any questions feel free to email me at dlannan at gagagames dot com
Cheers,
Dave

**Comment by Thomas12** [comment] 2015-03-03 23:58
Hi,


I am currently trying to get websockets working on Windows 8.1 32 Bit via MinGW.
I took a fresh 1.1-beta6 and replaced all problematic areas with either some parts of webdruino's turbolua 1.0.0 (win/ioloop.lua, win/iostream.lua) and made some hacks regarding "lssl" openssl (ssleay32, libeay32) and also removed the problematic fs.stat to just load to a buffer. Static file serving works but as soon as I connect via websocket I get this:

    2015/03/04 00:38:43] [web.lua] Added www/websock.html (1604 bytes) to static file cache.
    2015/03/04 00:38:43] [web.lua] 200 OK GET /websock.html (nil) 
    2015/03/04 00:38:43] [websocket.lua] WebSocket opened /ws (nil)
    2015/03/04 00:38:43] [web.lua] .\turbo\win\iostream.lua:825: Socket operation on closed stream.
    stack traceback:
            .\turbo\web.lua:1128: in function 'request_callback'
            .\turbo\httpserver.lua:251: in function <.\turbo\httpserver.lua:212>
            [C]: in function 'xpcall'
            .\turbo\win\iostream.lua:493: in function <.\turbo\win\iostream.lua:483>
            [C]: in function 'xpcall'
            .\turbo\win\ioloop.lua:533: in function <.\turbo\win\ioloop.lua:532>
    2015/03/04 00:38:43] [web.lua] 500 Internal Server Error GET /ws (nil) 0ms
    2015/03/04 00:38:43] [websocket.lua] WebSocket closed /ws (nil) 0ms

What could unexpectedly close the socket - any hints or ideas? What could be wrong?



Thank you!


Thomas

**Comment by kernelsauce** [comment] 2015-03-04 09:22
If you could add your websocket code it would be easier to help you :). But from what I'm seeing in your logs it seems like the client is disconnecting unexpectedly. Might be it does not get a valid websocket protocol handshake back? It crashes right after it sends the regular HTTP upgrade headers it seems. It might be down to your mix of components also...

**Comment by dlannan** [comment] 2015-03-04 09:23
Hi Thomas,
That looks alot like a problem with the ioloop process side.
I had to do a fair bit of massaging the io socket callbacks.
I suspect MingW is using different sockets and process control than the windows ones I was binding to. 
I'll have a look at it this weekend.
Cheers,




dlannan

From: Thomas12
Date: 2015-03-04 09:58
To: kernelsauce/turbo
CC: dlannan
Subject: Re: [turbo] Win Turbo - sort of. (#145)
Hi,
I am currently trying to get websockets working on Windows 8.1 32 Bit via MinGW.
I took a fresh 1.1-beta6 and replaced all problematic areas with either some parts of webdruino's turbolua 1.0.0 (win/ioloop.lua, win/iostream.lua) and made some hacks regarding "lssl" openssl (ssleay32, libeay32) and also removed the problematic fs.stat to just load to a buffer. Static file serving works but as soon as I connect via websocket I get this:
2015/03/04 00:38:43] [web.lua] Added www/websock.html (1604 bytes) to static file cache.
2015/03/04 00:38:43] [web.lua] 200 OK GET /websock.html (nil) 
2015/03/04 00:38:43] [websocket.lua] WebSocket opened /ws (nil)
2015/03/04 00:38:43] [web.lua] .\turbo\win\iostream.lua:825: Socket operation on closed stream.
stack traceback:
        .\turbo\web.lua:1128: in function 'request_callback'
        .\turbo\httpserver.lua:251: in function <.\turbo\httpserver.lua:212>
        [C]: in function 'xpcall'
        .\turbo\win\iostream.lua:493: in function <.\turbo\win\iostream.lua:483>
        [C]: in function 'xpcall'
        .\turbo\win\ioloop.lua:533: in function <.\turbo\win\ioloop.lua:532>
2015/03/04 00:38:43] [web.lua] 500 Internal Server Error GET /ws (nil) 0ms
2015/03/04 00:38:43] [websocket.lua] WebSocket closed /ws (nil) 0ms

What could unexpectedly close the socket - any hints or ideas? What could be wrong?
Thank you!
Thomas

**Comment by dlannan** [comment] 2015-03-04 10:07
Ahh. Interesting. 
Yes it could be the http response code - I tried to leave much of that alone tho. It could even be some stupid timing issue too.
As I mentioned, I'll try to have a look at it on the weekend. My work is flooding my spare time at the moment (trying to build a new simulator).




dlannan

From: John Abrahamsen
Date: 2015-03-04 19:22
To: kernelsauce/turbo
CC: dlannan
Subject: Re: [turbo] Win Turbo - sort of. (#145)
If you could add your websocket code it would be easier to help you :). But from what I'm seeing in your logs it seems like the client is disconnecting unexpectedly. Might be it does not get a valid websocket protocol handshake back? It crashes right after it sends the regular HTTP upgrade headers it seems. It might be down to your mix of components also...

**Comment by Thomas12** [comment] 2015-03-04 12:13
Thank you very much for your answers!

I setup a second PC, as local loop traffic is not visible in windows.
The last thing I see in wireshark is the GET /ws with "Upgrade: websocket" in its header.
No response after that request. And 0.01 seconds after this get-request, get a FIN message from the PC where turbolua is running for this websocket-upgrade-request.

When I directly call "/ws" in my browser I get this answer which gives some hope that the goal is near: 

    Expected a valid "Upgrade" HTTP header.

The websocket-script is very simple - works on Linux.

    ...
    local WSExHandler = class("WSExHandler", turbo.websocket.WebSocketHandler)
    
    function WSExHandler:open()
    print("on open");
    end
    
    function WSExHandler:on_close()
    print("on close");
    end
    
    function WSExHandler:on_message(msg)  
    print("on msg");
    end                                                                                                                                     
    
    local app=turbo.web.Application:new({
        {"^/ws$", WSExHandler}
    });


What I see right now after comparing the outputs is that the log-output from windows does not show the ip address in brackets - they are just nil - maybe a reason to abort?

I am also open for a non-MinGW approach, need to know how to setup the build-environment.

For my test I've also tried your luajit.exe, sys.dll, tffi_wrap.dll you ship in release/bin/win32 - same result.

**Comment by dlannan** [comment] 2015-03-04 13:59
Ahh no IP. Thats very interesting. 
According to rfc - WebSocket protocol... 
https://tools.ietf.org/html/rfc6455
1.2 Protocol Overview -> a few lines after
I think the header may need to support this format? It might be the browser (is it Firefox or Chrome - new versions?). 
Should be easy enough to fix I think. Although seems odd it works ok on Linux? Maybe there is some encoding issue on Windoze? Im not certain here.
Hrm.. could it be something evil like line endings? Did the 64 bit one work? Maybe its related to byte alignment or other wierdness - endianess? Are you using Intel x86?
CHeers,




dlannan

From: Thomas12
Date: 2015-03-04 21:13
To: kernelsauce/turbo
CC: dlannan
Subject: Re: [turbo] Win Turbo - sort of. (#145)
Thank you very much for your answers!
I setup a second PC, as local loop traffic is not visible in windows.
The last thing I see in wireshark is the GET /ws with "Upgrade: websocket" in its header.
No response after that request. And 0.01 seconds after this get-request, get a FIN message from the PC where turbolua is running for this websocket-upgrade-request.
When I directly call "/ws" in my browser I get this answer which gives some hope that the goal is near: 
Expected a valid "Upgrade" HTTP header.

The websocket-script is very simple - works on Linux.
...
local WSExHandler = class("WSExHandler", turbo.websocket.WebSocketHandler)

function WSExHandler:open()
print("on open");
end

function WSExHandler:on_close()
print("on close");
end

function WSExHandler:on_message(msg)  
print("on msg");
end                                                                                                                                     

local app=turbo.web.Application:new({
    {"^/ws$", WSExHandler}
});

What I see right now after comparing the outputs is that the log-output from windows does not show the ip address in brackets - they are just nil - maybe a reason to abort?
I am also open for a non-MinGW approach, need to know how to setup the build-environment.
For my test I've also tried your luajit.exe, sys.dll, tffi_wrap.dll you ship in release/bin/win32 - same result.

**Comment by Thomas12** [comment] 2015-03-04 14:28
Client is Firefox 36 on Windows 8.1 64 Bit, CPU=Intel 64 Bit. 
When turbolua is running on a Linux PC, websockets work flawlessly on this Windows client setup.
The normal turbolua 1.1-beta6 out of the box is working well on Linux.
On Windows I try to run turbolua-1.1-beta6 "patched" with your win-variants of ioloop.lua, sockutil.lua, etc. 
To run, I use the win32 luajit.exe, sys.dll from your /release/bin/win32.

And at least normal http and the websocket error message when manually connecting to a websocket URL via http work.

You are using turbolua 1.0.0, maybe some structs have changed in turbolua 1.1 that cause the abort or websockets are relying on a new and needed data-field that is not there in the turbolua 1.0.variants of your modified files like ioloop.lua.

At least the endianness of the SHA1-HMAC is correct, made a manual test in turbolua on Windows and against a SHA1-hmac web calculating service and the hex-string-result is identical.

I think just somewhere in the websocket code when evaluating the client headers requesting the upgrade to websockets cause the abort - because when you manually request the websocket-url over http you get a correct error message. 

Wanted to try the 64 bit variant of the luajit, sys.dll etc that you provide in your /release/bin/win64, but then I cannot load libeay32 anymore.

**Comment by kernelsauce** [comment] 2015-03-05 10:06
"Expected a valid "Upgrade" HTTP header." means the websocket handler got a HTTP request header without any "Upgrade" field. Basically that means its doing a regular HTTP request with no intention of upgrading protocol to Websockets, which you of course are doing when you direct the browser directly to a WS URL. The same will happen on Linux. :)

**Comment by Thomas12** [comment] 2015-03-05 11:55
I know, so at least websocket.lua is reacting and can understand and answer to basic things. 
Ok, when it is about real websocket stuff, it is still failing, but at least we see some valid interaction - no total loss and maybe the solution can be simple to get the rest working, too.

**Comment by Thomas12** [comment] 2015-03-05 18:47
I think the problem is that in function "websocket.WebSocketHandler:_execute()" the "self.stream:write" simply does not succeed. Putting a web.HTTPError at exactly that position where the websocket response_header is usually sent, gives me a normal http-answer when I connect via websockets - seen in wireshark as a http-answer here is invalid. And when I let it print the websocket response_header on the console, it looks valid. So everything is there, what fails is the self.stream:write, I think.

**Comment by kernelsauce** [comment] 2015-03-06 11:12
Check if the socket is closed at that point then. self.stream:closed() returns a boolean.

**Comment by Thomas12** [comment] 2015-03-06 11:44
Before and after write response_header, self.stream:closed() is FALSE, after self:_continue_ws() it is TRUE.

When I comment out self:_continue_ws(), I can now at least connect ONCE and the websocket-reply is valid. But after that, no more interaction is possible (sure, as _continue_ws is suppressed).

And in _continue_ws it is "self.stream:read_bytes(2, self._accept_frame, self)" that seems to be responsible for the disconnect - identified by commenting out each line in _continue_ws.

**Comment by kernelsauce** [comment] 2015-03-06 13:00
Okay. So it seems the connection is closed by the client after the first self.stream:write... And that is detected when the next write comes along :).

**Comment by Thomas12** [comment] 2015-03-06 13:37
I don't think it is the client as the server sends FIN first. And with _continue_ws enabled, the socket gets closed before the server even sent out the websocket upgrade answer, the client never gets this answer as the FIN comes first. Client sends GET /ws and besides a TCP ACK, the server just sends a FIN then.
And when you disable _continue_ws, the server sends its websocket upgrade answer and then neither client nor server do disconnect - so I think it comes from the server - related to something with _continue_ws.

And regarding the read_bytes function called from _continue_ws: The read_bytes function is executed completely until the end, but self._accept_frame is then never called.

As the windows-compatible basis is based on turbolua 1.0 and the websocket-feature seems to be a turbolua 1.1 feature, maybe something with the iostream/ioloop goes wrong as maybe some part must be websocket-aware or respect a certain websocket-topic... Or maybe the normal web-part of Version 1.0 is incompatible with the weboscket addon from Version 1.1, etc...

**Comment by Thomas12** [comment] 2015-03-06 14:18
The close that closes the connection is 
_continue_ws_  --> read_bytes --> _initial_read --> _read_to_buffer --> _read_from_socket

And in _read_from_socket from win/iostream.lua (about line 570) there is this
"if nsz<=0" then ...

followed by self:close()

nsz = -1

**Comment by kernelsauce** [comment] 2015-03-06 15:41
Ok. I cant really help you with that nsz check. Theres no such variable in the official iostream.lua source.

**Comment by Thomas12** [comment] 2015-03-06 22:18
When I just remove this "close", then it works. But when I reload the website, then I get errors on the lua console as it seems this close is indeed needed for other cases, like when the client really closes the connection. So the condition for this close must be redefined.

What's not working: Doing a self:write_message in the WSExHandler:on_message event does not work, but it works in other contexts like in a set_interval or in WSExHandler:open().

**Comment by Thomas12** [comment] 2015-03-08 19:54
Regarding the inability to do a self:write_message in WSExHandler:on_message(msg), I have to clarify:

As soon as WSExHandler:on_message(msg) is ever triggered, even when empty, leads to the problem that the self._write_buffer as for example seen in iostream.IOStream:write gets bigger and bigger with new messages and they are no longer really flushed to the client. Just connecting to the websocket server without ever triggering on_message works fine, (for example by sending messages to the client from within a timer event).

Also, as soon as you trigger a on_message event, the function _read_from_socket is triggered very often per second and permanently then with a nsz=-1 (remember, I have commented out the self:close out in _read_from_socket for snz<=0).

Maybe the problem with self:close and this problem here are belonging together.

**Comment by kernelsauce** [comment] 2015-03-10 20:44
I'm pleased to inform you that I've taken up releasing a official windows/mac/bsd client now. Development in the branch called luasocket :).

![capture](https://cloud.githubusercontent.com/assets/1081754/6584883/9901fc88-c76e-11e4-896d-233fa446d5f4.PNG)

This one will support WebSockets.

**Comment by Thomas12** [comment] 2015-03-11 00:16
Wow, very cool, will try that!

**Comment by Thomas12** [comment] 2015-03-11 01:11
I've tried it under mingw - had to move the cdef.lua-declarations for openssl (all where err_get_error is defined) out of the if-cluases to remove the "declaration not found"-error, but then I get a "procedure not found" error for SSL_get_error, although I changed lssl to load "libeay32" as "ssl" is not found (I have installed full openssl, not the minimal). In libeay32 I can at least see SSL_get_error via hex-editor, so seems to be defined... I wonder why the SSL_get_error can't be found...

**Comment by kernelsauce** [comment] 2015-03-11 05:54
OpenSSL is not supported in that branch yet.

**Comment by Thomas12** [comment] 2015-03-11 18:46
Ok, so I have to wait for openssl-support as axtls just does not want to compile under mingw (far too many different errors).

But I tried hellworld.lua and httpserver.lua (no websocket) - both do neither work in Firefox 36 nor IE 11, but they work in plain telnet test (GET / HTTP/1.1) - looks valid to me:

    HTTP/1.1 200 OK
    Server: Turbo.lua v1.1
    Content-Type: text/html; charset=UTF-8
    Content-Length: 12
    Date: Wed, 11 Mar 2015 19:33:08 GMT

    Hello World!

I've also deactivated the Windows firewall...

**Comment by Thomas12** [comment] 2015-03-12 11:47
Problem solved (must explicitly bind to "0.0.0.0"), I think an IPv6 issue.

**Comment by kernelsauce** [comment] 2015-03-12 11:52
LuaSocket will no doubt have a somewhat different API than the C bind function... So yes there are some kwirks atm.

**Comment by Thomas12** [comment] 2015-03-12 19:24
I managed to run it now even with openssl, just had to load libeay32 and ssleay and just commented out the error-messaging-problem. websockets work, but not very reliable - have to click exactly 3 times on localhost or 192.168... browser-client to actually trigger an on_message server event and to see a websocket-message response in the browser.
(Same 3x click problem in both Firefox 36 and IE 11 both on Win 8.1), websockets messages are sent from browser via normal websocket.send(message).

Sometimes in console log and not timely related to the 3x click issue:  Handler error: .\turbo\iostream.lua:657: Error when reading from socket tcp{client}: closed.

(Another issue: stat command for static file serving does not work on Windows).

I know it is all in early development stage - just a feedback for you.

**Comment by kernelsauce** [comment] 2015-03-12 20:53
Yes thank you. I know a lot is not working at the moment.

**Comment by kernelsauce** [comment] 2015-03-13 16:39
Thomas12, you could try pulling from luasocket branch now and retest websocket. I just fixed a whole bunch of issues which were related to reading and writing of data.

**Comment by Thomas12** [comment] 2015-03-13 18:29
I've made some tests now and it works very well, could not find websocket-related bugs in IE11 and FF36.

**Comment by kernelsauce** [comment] 2015-03-13 20:24
Great

**Comment by kernelsauce** [comment] 2015-03-16 21:31
I made a "installer" sort of for a full Turbo environment of Windows.

It uses chocolatey to install Visual Studio, git, mingw and other dependencies.

It compiles luajit, turbo, and luarocks.

Installs luasocket through luarocks.

Sets all env. variables for Lua and allows you to run the included examples of Turbo straight off... Everything is installed at C:\turbo.lua and you end up with a functioning LuaJIT amd64 and Luarocks installation.

This one-liner start the process using a admin elevated command prompt from windows 7 and upwards; powershell -command "& { iwr https://raw.githubusercontent.com/kernelsauce/turbo/luasocket/install.bat -OutFile turbo-install.bat }" && turbo-install.bat

Please be carefull. This is not very well tested at the moment, and it is probably best to try it in a VM.

**Comment by Thomas12** [comment] 2015-03-16 21:55
Wow, that is very nice!

**Comment by kernelsauce** [comment] 2015-03-19 20:05
Some fixes has been made for websockets now. And also the Static handler will work on Windows. You must have installed the luafilesystem  module via luarocks though. It is added in the install.bat installation file.

**Comment by Thomas12** [comment] 2015-03-20 00:08
Thank you, I will test that this weekend!

**Comment by kernelsauce** [comment] 2015-04-17 17:40
Those who wanted Windows support, you have it.

Use the included install.bat file or one line downloader:

    powershell -command "& { iwr https://raw.githubusercontent.com/kernelsauce/turbo/luasocket/install.bat OutFile t.bat }" && t.bat

This will install all dependencies: Visual Studio, git, mingw, gnuwin, openssl using Chocolatey. LuaJIT, the LuaRocks package manager and Turbo will be installed at C:\\turbo.lua. It will also install LuaSocket and LuaFileSystem with LuaRocks. The Windows environment will be ready to use upon success.

Try: luajit C:\turbo.lua\src\turbo\examples\helloworld.lua

If any of the .dll or. so's are placed at non-default location then use environment variables to point to the correct place:

E.g: SET TURBO_LIBTFFI=C:\turbo.lua\src\turbo\libtffi_wrap.dll and SET TURBO_LIBSSL=C:\Program Files\OpenSSL\libeay32.dll

Please read http://turbolua.org/doc/get_started.html#installing-turbo for more information.

Closing issue.

**Closed** 2015-04-17 17:41 UTC
Labels: Feature, Windows only
